# # Controle de erros com try.. except.. finally (Exceptions)
# try:
#     print(nome)
# except:
#     print('Aconteceu um erro')
#
# print('Terminou')

# # Tratamento com varias exceções
# try:
#     print(nome)
# except NameError:
#     print('Variavel inexistente')
# except:
#     print('Aconteceu qualquer coisa')

# # utilizando else
# try:
#     print(nome)  # se não houver erro executa
# except:
#     print('Variavel inexistente')  # Se houver erro o executa
# else:
#     print('Não houve erro')  # se não houver erro executa

# # utilizando finally
# try:
#     print(nome)  # se não houver erro executa
# except:
#     print('Variavel inexistente')  # Se houver erro o executa
# finally:
#     print('Terminou')



